#!/bin/bash
#SBATCH --job-name=graph2tree_asdiv_full_dense
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-12:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o graph2tree_asdiv_full_dense.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry

python -m src.main -mode train -gpu 0 -embedding roberta -emb_name roberta-base -embedding_size 768 -hidden_size 384 \
-depth 2 -lr 8e-4 -emb_lr 1e-5 -batch_size 8 -epochs 50 -dataset cv_asdiv-a -full_cv -run_name graph2tree_run_cv_asdiv-a